public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        byte firstValue = 0;
        short secondValue = 32_000;
        int thirdValue = 2_000_000;
        long forthValue = 10_000_000;
        float fifthValue = 1.2f;
        double sixthValue = 2.8765434567;
        System.out.println("Значение перменной firstValue с типом byte равно " + firstValue);
        System.out.println("Значение перменной secondValue с типом short равно " + secondValue);
        System.out.println("Значение перменной thirdValue с типом int равно " + thirdValue);
        System.out.println("Значение перменной forthValue с типом long равно " + forthValue);
        System.out.println("Значение перменной fifthValue с типом float равно " + fifthValue);
        System.out.println("Значение перменной sixthValue с типом double равно " + sixthValue);
        System.out.println("Задание 2");
        float numberOne = 27.12f;
        long numberTwo = 987_678_965_549L;
        float numberThree = 2.786f;
        short numberFour = 569;
        short numberFive = -159;
        short numberSix = 27897;
        byte  numberSeven = 67;
        System.out.println("Задание 3");
        byte firstClass = 23;
        byte secondClass = 27;
        byte thirdClass = 30;
        int totalStudents = firstClass + secondClass + thirdClass;
        short totalPaper = 480;
        int paperPerStudent = totalPaper / totalStudents;
        System.out.println("На каждого ученика рассчитано " + paperPerStudent + " листов бумаги");
        System.out.println("Задание 4");
        byte capacityPerMinute = 16 / 2;
        int capacityPer20Minutes = capacityPerMinute * 20;
        int capacityPerDay = capacityPerMinute * 60 * 24;
        int capacityPer3Days = capacityPerDay * 3;
        long capacityPerMonth = capacityPer3Days * 10;
        System.out.println("За 20 минут машина произвела " + capacityPer20Minutes + " бутылок");
        System.out.println("За день машина произвела " + capacityPerDay + " бутылок");
        System.out.println("За за 3 дня машина произвела " + capacityPer3Days + " бутылок");
        System.out.println("За месяц машина произвела " + capacityPerMonth + " бутылок");
        System.out.println("Задание 5");
        byte cansOfPaint = 120;
        byte whitePaint = 2;
        byte brownPaint = 4;
        int numberOfClasses = cansOfPaint / (whitePaint + brownPaint);
        int totalWhitePaint = numberOfClasses * whitePaint;
        int totalBrownPaint = numberOfClasses * brownPaint;
        System.out.println("В школе, где " + numberOfClasses + " классов, нужно " + totalWhitePaint
                + " банок белой краски и " + totalBrownPaint + " банок коричневой краски.");
        System.out.println("Задание 6");
        byte bananaWeight = 80;
        byte bananaUnits = 5;
        int bananaTotal = bananaWeight * bananaUnits;
        byte milkWeight = 105;
        byte milkUnits = 2;
        int milkTotal = milkWeight * milkUnits;
        byte iceCreamWeight = 100;
        byte iceCreamUnits = 2;
        int iceCreamTotal =  iceCreamWeight * iceCreamUnits;
        byte eggsWeight = 70;
        byte eggsUnits = 4;
        int eggsTotal = eggsWeight * eggsUnits;
        int totalWeight = bananaTotal + milkTotal + iceCreamTotal + eggsTotal;
        System.out.println(totalWeight);
        System.out.println("Задание 7");
        int weightGoal = 7 * 1000;
        short weightMinus1 = 250;
        short weightMinus2 = 500;
        int resultInDays1 = weightGoal / weightMinus1;
        int resultInDays2 = weightGoal / weightMinus2;
        int averageResultInDays = (resultInDays1 + resultInDays2) / 2;
        System.out.println("Если спорстмен худеет на 250 грамм в день понадобится " + resultInDays1 + " дней");
        System.out.println("Если спорстмен худеет на 500 грамм в день понадобится " + resultInDays2 + " дней");
        System.out.println("В среднем понадобится " + averageResultInDays + " день");
        System.out.println("Задание 8");
        int mashaSalary = 67_760;
        int denisSalary = 83_690;
        int kristinaSalary = 76_230;
        int annualIncome = mashaSalary + denisSalary + kristinaSalary;
        float raising = 1 + 0.1f;
        double mashaNewSalary = mashaSalary * raising;
        double denisNewSalary = denisSalary * raising;
        double kristinaNewSalary = kristinaSalary * raising;
        double annualIncomeAfterRaising = mashaNewSalary + denisNewSalary + kristinaNewSalary;
        double differenceInAnnualIncome = annualIncomeAfterRaising - annualIncome;
        System.out.println("После повышения Маша будет получать " + mashaNewSalary);
        System.out.println("После повышения Денис будет получать " + denisNewSalary);
        System.out.println("После повышения Кристина будет получать " + kristinaNewSalary);
        System.out.println("Разница в годовом доходе составит " + differenceInAnnualIncome);
    }
}